// packages/create-content-sdk-app/src/templates/angular/src/app/components/container.component.ts
import { Component, computed } from '@angular/core';
import { NgTemplateOutlet, NgStyle } from '@angular/common';
import { ScPlaceholderComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

const mediaUrlPattern = /mediaurl="([^"]*)"/i;

@Component({
  selector: 'app-container',
  imports: [NgTemplateOutlet, NgStyle, ScPlaceholderComponent],
  template: `
    @if (needsWrapper()) {
    <div class="container-wrapper">
      <ng-container *ngTemplateOutlet="containerInner"></ng-container>
    </div>
    } @else {
    <ng-container *ngTemplateOutlet="containerInner"></ng-container>
    }

    <ng-template #containerInner>
      <div
        [attr.class]="('component container-default ' + styles()).trim()"
        [attr.id]="renderingId()"
      >
        <div class="component-content" [ngStyle]="backgroundStyle()">
          <div class="row">
            @if (placeholderName()) {
            <sc-placeholder [name]="placeholderName()!" [rendering]="rendering()!"></sc-placeholder>
            }
          </div>
        </div>
      </div>
    </ng-template>
  `,
})
export class ContainerComponent extends SxaComponent {
  readonly placeholderName = computed(() => {
    const id = this.params()?.DynamicPlaceholderId?.trim();
    return id ? `container-${id}` : '';
  });

  readonly needsWrapper = computed(() => {
    const tokens = this.styles()?.split(/\s+/).filter(Boolean) ?? [];
    return tokens.includes('container');
  });

  readonly backgroundStyle = computed((): { [key: string]: string } => {
    const backgroundImage = this.params()?.BackgroundImage;
    if (!backgroundImage || !mediaUrlPattern.test(backgroundImage)) {
      return {};
    }
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.at(1) ?? '';
    if (!mediaUrl) {
      return {};
    }
    return {
      backgroundImage: `url('${mediaUrl}')`,
    };
  });
}

export default ContainerComponent;

// packages/create-sitecore-jss/src/templates/nextjs/src/components/Container.tsx
﻿import { Placeholder } from '@sitecore-content-sdk/nextjs';
import React, { JSX } from 'react';
import { ComponentProps } from 'lib/component-props';

interface ContainerProps extends ComponentProps {
  params: ComponentProps['params'] & {
    BackgroundImage?: string;
    DynamicPlaceholderId: string;
  };
}

const Container = ({ params, rendering }: ContainerProps): JSX.Element => {
  const {
    styles,
    RenderingIdentifier: id,
    BackgroundImage: backgroundImage,
    DynamicPlaceholderId,
  } = params;
  const phKey = `container-${DynamicPlaceholderId}`;

  // Extract the mediaurl from rendering parameters
  const mediaUrlPattern = new RegExp(/mediaurl=\"([^"]*)\"/, 'i');

  let backgroundStyle: { [key: string]: string } = {};

  if (backgroundImage && backgroundImage.match(mediaUrlPattern)) {
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.[1] || '';

    backgroundStyle = {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }

  return (
    <div className={`component container-default ${styles}`} id={id}>
      <div className="component-content" style={backgroundStyle}>
        <div className="row">
          <Placeholder name={phKey} rendering={rendering} />
        </div>
      </div>
    </div>
  );
};

export const Default = (props: ContainerProps): JSX.Element => {
  const styles = props.params?.styles?.split(' ');

  return styles?.includes('container') ? (
    <div className="container-wrapper">
      <Container {...props} />
    </div>
  ) : (
    <Container {...props} />
  );
};
