// packages/create-content-sdk-app/src/templates/angular/src/app/components/image/image.component.ts
import { Component, OnInit, ViewChild, TemplateRef, effect, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  EditMode,
  ImageField,
  SitecoreContextService,
  ImageComponent as CSDKImageComponent,
  TextComponent,
  LinkComponent,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
  standalone: true,
  imports: [CommonModule, CSDKImageComponent, TextComponent, LinkComponent],
})
export class ImageComponent extends SxaComponent implements OnInit {
  @ViewChild('default', { static: true }) defaultVariant!: TemplateRef<unknown>;
  @ViewChild('banner', { static: true }) bannerVariant!: TemplateRef<unknown>;
  classHeroBannerEmpty = '';
  backgroundStyle: Record<string, string> = {};
  modifyImageProps: ImageField | Record<string, unknown> = {};
  isEditing = false;

  constructor() {
    super();
    const sitecoreContext = inject(SitecoreContextService);
    // React to context changes using effect
    effect(() => {
      const page = sitecoreContext.page();
      this.isEditing = page?.mode?.isEditing ?? false;
      this.updateImageProps(page?.layout?.sitecore?.context?.editMode);
    });
  }

  override ngOnInit() {
    super.ngOnInit();

    const imageField = this.rendering.fields?.Image as ImageField | undefined;
    this.backgroundStyle = imageField?.value?.src
      ? { 'background-image': `url('${imageField.value.src}')` }
      : {};
  }

  private updateImageProps(editMode?: unknown): void {
    const imageField = this.rendering.fields?.Image as ImageField | undefined;

    if (imageField) {
      this.classHeroBannerEmpty =
        this.isEditing && imageField.value?.class === 'scEmptyImage' ? 'hero-banner-empty' : '';

      const isMetadataMode = (editMode as EditMode | undefined) === EditMode.Metadata;
      this.modifyImageProps = isMetadataMode
        ? {
            ...imageField,
            value: {
              ...imageField.value,
              style: { width: '100%', height: '100%' },
            },
          }
        : imageField;
    }
  }

  public get variant(): TemplateRef<unknown> {
    return this.rendering.params?.FieldNames === 'Banner'
      ? this.bannerVariant
      : this.defaultVariant;
  }
}

<ng-container [ngTemplateOutlet]="variant"></ng-container>

<ng-template #default>
  <div class="component image {{ styles }}" [attr.id]="id" *ngIf="rendering.fields; else empty">
    <div class="component-content">
      @if (isEditing || !$any(rendering.fields)?.TargetUrl?.value?.href) {
      <sc-image field="imageField"></sc-image>
      } @else {
      <sc-link field="TargetUrl">
        <sc-image field="imageField"></sc-image>
      </sc-link>
      }
      <span class="image-caption field-imagecaption">
        <sc-text field="ImageCaption"></sc-text>
      </span>
    </div>
  </div>
</ng-template>

<ng-template #banner>
  <div class="component hero-banner {{ styles }} {{ classHeroBannerEmpty }}" [attr.id]="id">
    <div class="component-content sc-sxa-image-hero-banner" [ngStyle]="backgroundStyle">
      @if (isEditing) {
      <sc-image field="Image"></sc-image>
      }
    </div>
  </div>
</ng-template>

<ng-template #withLink>
  <sc-link field="TargetUrl">
    <sc-image field="Image"></sc-image>
  </sc-link>
</ng-template>

<ng-template #empty>
  <div class="component image {{ styles }}">
    <div class="component-content">
      <span class="is-empty-hint">Image</span>
    </div>
  </div>
</ng-template>

// packages/create-sitecore-jss/src/templates/nextjs/src/components/Image.tsx
﻿import {
  Field,
  ImageField,
  NextImage as JssImage,
  Link as JssLink,
  LinkField,
  Text,
  useSitecoreContext,
} from '@sitecore-content-sdk/nextjs';
import React, { CSSProperties } from 'react';

interface Fields {
  Image: ImageField & { metadata?: { [key: string]: unknown } };
  ImageCaption: Field<string>;
  TargetUrl: LinkField;
}

type ImageProps = {
  params: { [key: string]: string };
  fields: Fields;
};

const ImageDefault = (props: ImageProps): JSX.Element => (
  <div className={`component image ${props.params.styles}`.trimEnd()}>
    <div className="component-content">
      <span className="is-empty-hint">Image</span>
    </div>
  </div>
);

export const Banner = (props: ImageProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  const { sitecoreContext } = useSitecoreContext();
  const isPageEditing = sitecoreContext.pageEditing;
  const classHeroBannerEmpty =
    isPageEditing && props.fields?.Image?.value?.class === 'scEmptyImage'
      ? 'hero-banner-empty'
      : '';
  const backgroundStyle = (props?.fields?.Image?.value?.src && {
    backgroundImage: `url('${props.fields.Image.value.src}')`,
  }) as CSSProperties;
  const modifyImageProps = {
    ...props.fields.Image,
    value: {
      ...props.fields.Image.value,
      style: { width: '100%', height: '100%' },
    },
  };

  return (
    <div
      className={`component hero-banner ${props.params.styles} ${classHeroBannerEmpty}`}
      id={id ? id : undefined}
    >
      <div className="component-content sc-sxa-image-hero-banner" style={backgroundStyle}>
        {sitecoreContext.pageEditing ? <JssImage field={modifyImageProps} /> : ''}
      </div>
    </div>
  );
};

export const Default = (props: ImageProps): JSX.Element => {
  const { sitecoreContext } = useSitecoreContext();

  if (props.fields) {
    const Image = () => <JssImage field={props.fields.Image} />;
    const id = props.params.RenderingIdentifier;

    return (
      <div className={`component image ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          {sitecoreContext.pageState === 'edit' || !props.fields.TargetUrl?.value?.href ? (
            <Image />
          ) : (
            <JssLink field={props.fields.TargetUrl}>
              <Image />
            </JssLink>
          )}
          <Text
            tag="span"
            className="image-caption field-imagecaption"
            field={props.fields.ImageCaption}
          />
        </div>
      </div>
    );
  }

  return <ImageDefault {...props} />;
};
