// samples/angular/src/components/link-list/link-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Field,
  LinkField,
  ComponentFields,
  ScTextDirective,
  ScLinkDirective,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-link-list',
  templateUrl: './link-list.component.html',
  standalone: true,
  imports: [CommonModule, ScTextDirective, ScLinkDirective],
  host: {
    class: 'component link-list',
    '[class]': 'styles',
    '[attr.id]': 'id',
  },
})
export class LinkListComponent extends SxaComponent<ComponentFields> implements OnInit {
  title?: Field<string>;
  fieldLinks: LinkField[] = [];

  getFieldLinkClass(index: number): string {
    let className = `item${index}`;
    className += (index + 1) % 2 === 0 ? ' even' : ' odd';
    if (index === 0) {
      className += ' first';
    }
    if (index + 1 === this.fieldLinks.length) {
      className += ' last';
    }
    return className;
  }

  override ngOnInit() {
    super.ngOnInit();
    const datasource = (this.rendering.fields as any)?.data?.datasource;
    if (datasource) {
      this.title = datasource.field?.title as Field<string>;
      datasource.children.results.forEach((item: any) => {
        if (item.field?.link) this.fieldLinks.push(item.field.link as LinkField);
      });
    }
  }
}

// packages/create-sitecore-jss/src/templates/nextjs/src/components/LinkList.tsx
﻿import React from 'react';
import {
  Link as JssLink,
  Text,
  LinkField,
  TextField,
} from '@sitecore-content-sdk/nextjs';

type ResultsFieldLink = {
  field: {
    link: LinkField;
  };
};

interface Fields {
  data: {
    datasource: {
      children: {
        results: ResultsFieldLink[];
      };
      field: {
        title: TextField;
      };
    };
  };
}

type LinkListProps = {
  params: { [key: string]: string };
  fields: Fields;
};

type LinkListItemProps = {
  key: string;
  index: number;
  total: number;
  field: LinkField;
};

const LinkListItem = (props: LinkListItemProps) => {
  let className = `item${props.index}`;
  className += (props.index + 1) % 2 == 0 ? ' even' : ' odd';
  if (props.index == 0) {
    className += ' first';
  }
  if (props.index + 1 == props.total) {
    className += ' last';
  }
  return (
    <li className={className}>
      <div className="field-link">
        <JssLink field={props.field} />
      </div>
    </li>
  );
};

export const Default = (props: LinkListProps): JSX.Element => {
  const datasource = props.fields?.data?.datasource;
  const styles = `component link-list ${props.params.styles}`.trimEnd();
  const id = props.params.RenderingIdentifier;

  if (datasource) {
    const list = datasource.children.results
      .filter((element: ResultsFieldLink) => element?.field?.link)
      .map((element: ResultsFieldLink, key: number) => (
        <LinkListItem
          index={key}
          key={`${key}${element.field.link}`}
          total={datasource.children.results.length}
          field={element.field.link}
        />
      ));

    return (
      <div className={styles} id={id ? id : undefined}>
        <div className="component-content">
          <Text tag="h3" field={datasource?.field?.title} />
          <ul>{list}</ul>
        </div>
      </div>
    );
  }

  return (
    <div className={styles} id={id ? id : undefined}>
      <div className="component-content">
        <h3>Link List</h3>
      </div>
    </div>
  );
};
