// packages/create-content-sdk-app/src/templates/angular/src/app/components/promo/promo.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ImageComponent,
  RichTextComponent,
  LinkComponent,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-promo',
  templateUrl: './promo.component.html',
  standalone: true,
  imports: [CommonModule, ImageComponent, RichTextComponent, LinkComponent],
  host: {
    class: 'component promo',
    '[class]': 'styles',
    '[id]': 'id',
  },
})
export class PromoComponent extends SxaComponent {}

<div class="component-content">
  @if (rendering.fields) {
  <div class="field-promoicon">
    <sc-image [field]="$any(rendering.fields).PromoIcon"></sc-image>
  </div>
  <div class="promo-text">
    <div>
      <div class="field-promotext">
        <sc-rich-text [field]="$any(rendering.fields).PromoText"></sc-rich-text>
      </div>
    </div>
    <div class="field-promolink">
      <sc-link [field]="$any(rendering.fields).PromoLink"></sc-link>
    </div>
  </div>
  } @else {
  <span class="is-empty-hint">Promo</span>
  }
</div>

// packages/create-sitecore-jss/src/templates/nextjs/src/components/Promo.tsx
﻿import React, { JSX } from 'react';
import {
  NextImage as JssImage,
  Link as JssLink,
  RichText as JssRichText,
  ImageField,
  Field,
  LinkField,
} from '@sitecore-content-sdk/nextjs';

interface Fields {
  PromoIcon: ImageField;
  PromoText: Field<string>;
  PromoLink: LinkField;
  PromoText2: Field<string>;
}

type PromoProps = {
  params: { [key: string]: string };
  fields: Fields;
};

const PromoDefaultComponent = (props: PromoProps): JSX.Element => (
  <div className={`component promo ${props.params.styles}`}>
    <div className="component-content">
      <span className="is-empty-hint">Promo</span>
    </div>
  </div>
);

export const Default = (props: PromoProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  if (props.fields) {
    return (
      <div className={`component promo ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          <div className="field-promoicon">
            <JssImage field={props.fields.PromoIcon} />
          </div>
          <div className="promo-text">
            <div>
              <div className="field-promotext">
                <JssRichText field={props.fields.PromoText} />
              </div>
            </div>
            <div className="field-promolink">
              <JssLink field={props.fields.PromoLink} />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return <PromoDefaultComponent {...props} />;
};

export const WithText = (props: PromoProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  if (props.fields) {
    return (
      <div className={`component promo ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          <div className="field-promoicon">
            <JssImage field={props.fields.PromoIcon} />
          </div>
          <div className="promo-text">
            <div>
              <div className="field-promotext">
                <JssRichText className="promo-text" field={props.fields.PromoText} />
              </div>
            </div>
            <div className="field-promotext">
              <JssRichText className="promo-text" field={props.fields.PromoText2} />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return <PromoDefaultComponent {...props} />;
};
