// packages/create-content-sdk-app/src/templates/angular/src/app/components/richtext/richtext.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RichTextField, RichTextComponent as CSDKRichTextComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-richtext',
  templateUrl: './richtext.component.html',
  standalone: true,
  imports: [CommonModule, CSDKRichTextComponent],
  host: {
    class: 'component rich-text',
    '[class]': 'styles',
    '[attr.id]': 'id',
  },
})
export class RichTextComponent extends SxaComponent implements OnInit {
  text?: RichTextField;

  override ngOnInit() {
    super.ngOnInit();
    this.text = this.rendering.fields?.Text as RichTextField;
  }
}

<div class="component-content">
  @if (text) {
  <sc-rich-text [field]="text"></sc-rich-text>
  } @else {
  <span class="is-empty-hint">Rich text</span>
  }
</div>

// packages/create-sitecore-jss/src/templates/nextjs/src/components/RichText.tsx
﻿import React from 'react';
import { Field, RichText as JssRichText } from '@sitecore-content-sdk/nextjs';

interface Fields {
  Text: Field<string>;
}

export type RichTextProps = {
  params: { [key: string]: string };
  fields: Fields;
};

export const Default = (props: RichTextProps): JSX.Element => {
  const text = props.fields ? (
    <JssRichText field={props.fields.Text} />
  ) : (
    <span className="is-empty-hint">Rich text</span>
  );
  const id = props.params.RenderingIdentifier;

  return (
    <div
      className={`component rich-text ${props.params.styles.trimEnd()}`}
      id={id ? id : undefined}
    >
      <div className="component-content">{text}</div>
    </div>
  );
};
