// packages/create-content-sdk-app/src/templates/angular/src/app/components/row-splitter.component.ts
import { Component, computed } from '@angular/core';
import { ScPlaceholderComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

type RowNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

@Component({
  selector: 'app-row-splitter',
  imports: [ScPlaceholderComponent],
  template: `
    <div [attr.class]="('component row-splitter ' + styles()).trim()" [attr.id]="renderingId()">
      @for (placeholderSegment of enabledPlaceholders(); track placeholderSegment) {
      <div [attr.class]="rowSectionClass(placeholderSegment)">
        <div>
          <div class="row">
            <sc-placeholder
              [name]="placeholderKey(placeholderSegment)"
              [rendering]="rendering()!"
            ></sc-placeholder>
          </div>
        </div>
      </div>
      }
    </div>
  `,
})
export class RowSplitterComponent extends SxaComponent {
  readonly enabledPlaceholders = computed(() => {
    const raw = this.params()?.EnabledPlaceholders;
    return (
      raw
        ?.split(',')
        .map((segment: string) => segment.trim())
        .filter(Boolean) ?? []
    );
  });

  placeholderKey(placeholderSegment: string): string {
    const rowIndex = Number(placeholderSegment) as RowNumber;
    return `row-${rowIndex}-{*}`;
  }

  rowSectionClass(placeholderSegment: string): string {
    const rowIndex = Number(placeholderSegment) as RowNumber;
    const rowStyles = `${this.params()?.[`Styles${rowIndex}`] ?? ''}`.trimEnd();
    return `container-fluid ${rowStyles}`.trimEnd();
  }
}

// packages/create-sitecore-jss/src/templates/nextjs/src/components/RowSplitter.tsx
﻿import React, { JSX } from 'react';
import {
  ComponentParams,
  ComponentRendering,
  Placeholder,
} from '@sitecore-content-sdk/nextjs';

interface ComponentProps {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
}

export const Default = (props: ComponentProps): JSX.Element => {
  const styles = `${props.params.GridParameters ?? ''} ${props.params.Styles ?? ''}`.trimEnd();
  const rowStyles = [
    props.params.Styles1,
    props.params.Styles2,
    props.params.Styles3,
    props.params.Styles4,
    props.params.Styles5,
    props.params.Styles6,
    props.params.Styles7,
    props.params.Styles8,
  ];
  const enabledPlaceholders = props.params.EnabledPlaceholders.split(',');
  const id = props.params.RenderingIdentifier;

  return (
    <div className={`component row-splitter ${styles}`} id={id ? id : undefined}>
      {enabledPlaceholders.map((ph, index) => {
        const phKey = `row-${ph}-{*}`;
        const phStyles = `${rowStyles[+ph - 1] ?? ''}`.trimEnd();

        return (
          <div key={index} className={`container-fluid ${phStyles}`.trimEnd()}>
            <div key={index}>
              <div key={index} className="row">
                <Placeholder key={index} name={phKey} rendering={props.rendering} />
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
};
