// packages/create-content-sdk-app/src/templates/nextjs-app-router (beta)/src/components/skatepark/Promo.tsx
import React from 'react';
import {
  ComponentParams,
  ComponentRendering,
  Image,
  Link,
  RichText,
} from '@sitecore-content-sdk/nextjs';

interface Fields {
  promoIcon: {
    value: {
      src: string;
      alt: string;
    };
  };
  promoText: { value: string };
  promoLink: {
    value: {
      href: string;
      text: string;
    };
  };
}

type PromoProps = {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
  fields: Fields;
};

export const Promo = (props: PromoProps) => {
  const { promoIcon, promoText, promoLink } = props.fields || {};

  return (
    <div className="component promo">
      <div className="component-content">
        {promoIcon && (
          <div className="promo-icon">
            <Image field={promoIcon} />
          </div>
        )}
        <div className="promo-text">
          {promoText && (
            <div className="promo-text-content">
              <RichText field={promoText} />
            </div>
          )}
          {promoLink && (
            <div className="promo-link">
              <Link field={promoLink} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// packages/create-content-sdk-app/src/templates/angular/src/app/components/promo/promo.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ImageComponent,
  RichTextComponent,
  LinkComponent,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-promo',
  templateUrl: './promo.component.html',
  standalone: true,
  imports: [CommonModule, ImageComponent, RichTextComponent, LinkComponent],
  host: {
    class: 'component promo',
    '[class]': 'styles',
    '[id]': 'id',
  },
})
export class PromoComponent extends SxaComponent {}

<div class="component-content">
  @if (rendering.fields) {
  <div class="field-promoicon">
    <sc-image [field]="$any(rendering.fields).PromoIcon"></sc-image>
  </div>
  <div class="promo-text">
    <div>
      <div class="field-promotext">
        <sc-rich-text [field]="$any(rendering.fields).PromoText"></sc-rich-text>
      </div>
    </div>
    <div class="field-promolink">
      <sc-link [field]="$any(rendering.fields).PromoLink"></sc-link>
    </div>
  </div>
  } @else {
  <span class="is-empty-hint">Promo</span>
  }
</div>
