// packages/create-content-sdk-app/src/templates/nextjs-app-router-skatepark/src/components/column-splitter/ColumnSplitter.tsx
import React, { JSX } from 'react';
import Placeholder from 'components/content-sdk/Placeholder';
import { ComponentWithContextProps } from 'lib/component-props';
import { componentMap } from '.sitecore/component-map';

/**
 * The number of columns that can be inserted into the column splitter component.
 * The maximum number of columns is 8.
 */
type ColumnNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * The width specified for each rendered column.
 * The key is the column number, and the value is the width.
 */
type ColumnWidths = {
  [K in ColumnNumber as `ColumnWidth${K}`]?: string;
};

/**
 * The styles specified for each rendered column.
 * The key is the column number, and the value is the styles.
 */
type ColumnStyles = {
  [K in ColumnNumber as `Styles${K}`]?: string;
};

interface ColumnSplitterProps extends ComponentWithContextProps {
  params: ComponentWithContextProps['params'] & ColumnWidths & ColumnStyles;
}

export const Default = ({ params, rendering, page }: ColumnSplitterProps): JSX.Element => {
  const { EnabledPlaceholders, RenderingIdentifier: id, styles } = params;

  const enabledColumns = EnabledPlaceholders?.split(',') ?? [];

  return (
    <div className={`row component column-splitter ${styles}`} id={id}>
      {enabledColumns.map((columnNum, index) => {
        const num = Number(columnNum) as ColumnNumber;
        const columnWidth = params[`ColumnWidth${num}`] ?? '';
        const columnStyle = params[`Styles${num}`] ?? '';
        const columnClassNames = `${columnWidth} ${columnStyle}`.trim();

        return (
          <div key={index} className={columnClassNames}>
            <div className="row">
              <Placeholder
                name={`column-${columnNum}-{*}`}
                rendering={rendering}
                page={page}
                componentMap={componentMap}
              />
            </div>
          </div>
        );
      })}
    </div>
  );
};

// packages/create-content-sdk-app/src/templates/angular/src/app/components/column-splitter.component.ts
import { Component, computed } from '@angular/core';
import { ScPlaceholderComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';
type ColumnNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

@Component({
  selector: 'app-column-splitter',
  imports: [ScPlaceholderComponent],
  template: `
    <div
      [attr.class]="('row component column-splitter ' + styles()).trim()"
      [attr.id]="renderingId()"
    >
      @for (columnNum of enabledColumns(); track columnNum) {
      <div [attr.class]="columnClassNames(columnNum)">
        <div class="row">
          <sc-placeholder
            [name]="placeholderKey(columnNum)"
            [rendering]="rendering()!"
          ></sc-placeholder>
        </div>
      </div>
      }
    </div>
  `,
})
export class ColumnSplitterComponent extends SxaComponent {
  /** Enabled placeholder columns from params. */
  readonly enabledColumns = computed(() => {
    const raw = this.params()?.EnabledPlaceholders;
    return (
      raw
        ?.split(',')
        .map((segment: string) => segment.trim())
        .filter(Boolean) ?? []
    );
  });

  /** Extra root-level classes from rendering params (SXA: GridParameters + Styles). */
  override readonly styles = computed(() => {
    const renderingParams = this.params();
    const gridParams = renderingParams?.GridParameters?.trim() ?? '';
    const fromStyles = renderingParams?.Styles?.trim() ?? '';
    return `${gridParams} ${fromStyles}`.trim();
  });

  placeholderKey(columnNum: string): string {
    return `column-${columnNum}-{*}`;
  }

  columnClassNames(columnNum: string): string {
    const columnIndex = Number(columnNum) as ColumnNumber;
    const columnWidth = this.params()?.[`ColumnWidth${columnIndex}`] ?? '';
    const columnStyle = this.params()?.[`Styles${columnIndex}`] ?? '';
    return `${columnWidth} ${columnStyle}`.trim();
  }
}

export default ColumnSplitterComponent;
