// packages/create-content-sdk-app/src/templates/nextjs-app-router (beta)/src/components/skatepark/RichText.tsx
import React from 'react';
import {
  ComponentParams,
  ComponentRendering,
  RichText as SitecoreRichText,
} from '@sitecore-content-sdk/nextjs';

interface Fields {
  text: { value: string };
}

type RichTextProps = {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
  fields: Fields;
};

export const RichText = (props: RichTextProps) => {
  const { text } = props.fields || {};

  return (
    <div className="component rich-text">
      <div className="component-content">
        {text ? (
          <SitecoreRichText field={text} />
        ) : (
          <span className="is-empty-hint">Rich text</span>
        )}
      </div>
    </div>
  );
};

// packages/create-content-sdk-app/src/templates/angular/src/app/components/rich-text.component.ts
import { Component, input, computed } from '@angular/core';
import { ComponentRendering, Field } from '@sitecore-content-sdk/angular';
import { ScRichTextDirective } from '@sitecore-content-sdk/angular';
import { scComponentRoot, scRenderingId } from '../sitecore/sitecore-component-classes';

@Component({
  selector: 'app-rich-text',
  standalone: true,
  imports: [ScRichTextDirective],
  template: `
    <div [attr.class]="rootClass()" [id]="renderingId()">
      <div class="component-content">
        <div class="rich-text" [scRichText]="contentField()"></div>
      </div>
    </div>
  `,
})
export class RichTextComponent {
  readonly fields = input<{ [key: string]: unknown }>({});
  readonly params = input<{ [key: string]: string }>({});
  readonly rendering = input<ComponentRendering>();

  readonly contentField = computed(() => this.fields()?.['Text'] as Field<string> | undefined);

  readonly rootClass = computed(() => scComponentRoot('rich-text', this.params()));
  readonly renderingId = computed(() => scRenderingId(this.params()));
}
