// packages/create-sitecore-jss/src/templates/nextjs/src/components/Title.tsx
﻿import {
  Link,
  LinkField,
  Text,
  TextField,
  useSitecoreContext,
} from '@sitecore-content-sdk/nextjs';
import React from 'react';

interface Fields {
  data: {
    datasource: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
    contextItem: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
  };
}

type TitleProps = {
  params: { [key: string]: string };
  fields: Fields;
};

type ComponentContentProps = {
  id: string;
  styles: string;
  children: JSX.Element;
};

const ComponentContent = (props: ComponentContentProps) => {
  const id = props.id;
  return (
    <div className={`component title ${props.styles}`} id={id ? id : undefined}>
      <div className="component-content">
        <div className="field-title">{props.children}</div>
      </div>
    </div>
  );
};

export const Default = (props: TitleProps): JSX.Element => {
  const datasource = props.fields?.data?.datasource || props.fields?.data?.contextItem;
  const { sitecoreContext } = useSitecoreContext();
  const text: TextField = datasource?.field?.jsonValue || {};
  const link: LinkField = {
    value: {
      href: datasource?.url?.path,
      title: datasource?.field?.jsonValue?.value,
    },
  };
  if (sitecoreContext.pageState !== 'normal') {
    link.value.querystring = `sc_site=${datasource?.url?.siteName}`;
    if (!text?.value) {
      text.value = 'Title field';
      link.value.href = '#';
    }
  }

  return (
    <ComponentContent styles={props.params.styles} id={props.params.RenderingIdentifier}>
      <>
        {sitecoreContext.pageEditing ? (
          <Text field={text} />
        ) : (
          <Link field={link}>
            <Text field={text} />
          </Link>
        )}
      </>
    </ComponentContent>
  );
};

// samples/angular/src/app/components/title/title.component.ts
import { Component, OnInit, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  LinkField,
  TextField,
  ComponentFields,
  SitecoreContextService,
  ScTextDirective,
  ScLinkDirective,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-title',
  templateUrl: './title.component.html',
  standalone: true,
  imports: [CommonModule, ScTextDirective, ScLinkDirective],
  host: {
    class: 'component title',
    '[class]': 'styles',
    '[id]': 'id',
  },
})
export class TitleComponent extends SxaComponent<ComponentFields> implements OnInit {
  text?: TextField;
  link?: LinkField;
  pageEditing = false;

  constructor(sitecoreContext: SitecoreContextService) {
    super();

    // React to context changes using effect
    effect(() => {
      const page = sitecoreContext.page();
      if (page) {
        this.pageEditing = page.mode?.isEditing ?? false;
        this.updateLinkForEditing(page.mode?.isNormal === false);
      }
    });
  }

  override ngOnInit() {
    super.ngOnInit();
    const datasource =
      (this.rendering.fields as any)?.data?.datasource ||
      (this.rendering.fields as any)?.data?.contextItem;

    if (datasource) {
      this.text = datasource.field?.jsonValue;
      this.link = {
        value: {
          href: datasource?.url?.path,
          title: datasource?.field?.jsonValue?.value,
          text: datasource?.field?.jsonValue?.value,
        },
      };
    }
  }

  private updateLinkForEditing(isEditingMode: boolean): void {
    if (isEditingMode && this.link?.value) {
      const datasource =
        (this.rendering.fields as any)?.data?.datasource ||
        (this.rendering.fields as any)?.data?.contextItem;
      this.link.value.querystring = `sc_site=${datasource?.url?.siteName}`;
      if (!this.text?.value) {
        if (this.text) {
          this.text.value = 'Title field';
        }
        this.link.value.href = '#';
      }
    }
  }
}
