// packages/angular/src/lib/placeholder/placeholder-metadata.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ComponentRendering,
  isDynamicPlaceholder,
  getDynamicPlaceholderPattern,
} from '@sitecore-content-sdk/core/layout';
import { MetadataKind, DEFAULT_PLACEHOLDER_UID } from '@sitecore-content-sdk/core/editing';

/**
 * Code block attributes for metadata markers
 * @internal
 */
export interface CodeBlockAttributes {
  type: string;
  chrometype: 'placeholder' | 'rendering';
  class: string;
  kind: MetadataKind;
  id?: string;
}

/**
 * A component to generate metadata code blocks for a placeholder or rendering in editing mode.
 * It creates opening and closing code blocks with appropriate attributes.
 * @public
 */
@Component({
  selector: 'sc-placeholder-metadata',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <code
      type="text/sitecore"
      [attr.chrometype]="chromeType"
      class="scpm"
      [attr.kind]="openKind"
      [attr.id]="computedId"
    ></code>
    <ng-content></ng-content>
    <code
      type="text/sitecore"
      [attr.chrometype]="chromeType"
      class="scpm"
      [attr.kind]="closeKind"
    ></code>
  `,
})
export class PlaceholderMetadataComponent {
  /**
   * The rendering data for this component
   */
  @Input({ required: true }) rendering!: ComponentRendering;

  /**
   * The name of the placeholder (if this is a placeholder chrome)
   */
  @Input() placeholderName?: string;

  /**
   * MetadataKind.Open constant for template
   */
  protected readonly openKind = MetadataKind.Open;

  /**
   * MetadataKind.Close constant for template
   */
  protected readonly closeKind = MetadataKind.Close;

  /**
   * Computed chrome type based on whether this is a placeholder or rendering
   */
  protected get chromeType(): 'placeholder' | 'rendering' {
    return this.placeholderName ? 'placeholder' : 'rendering';
  }

  /**
   * Computed ID for the opening code block
   */
  protected get computedId(): string | undefined {
    if (this.chromeType === 'placeholder' && this.placeholderName) {
      return this.getPlaceholderId();
    }
    return this.rendering.uid;
  }

  /**
   * Get the placeholder ID for the metadata
   */
  private getPlaceholderId(): string {
    const placeholderName = this.placeholderName!;
    const id = this.rendering.uid;

    for (const placeholder of Object.keys(this.rendering.placeholders ?? {})) {
      if (placeholderName === placeholder) {
        return id
          ? `${placeholderName}_${id}`
          : `${placeholderName}_${DEFAULT_PLACEHOLDER_UID}`;
      }

      // Check if the placeholder is a dynamic placeholder
      if (isDynamicPlaceholder(placeholder)) {
        const pattern = getDynamicPlaceholderPattern(placeholder);

        // Check if the placeholder matches the dynamic placeholder pattern
        if (pattern.test(placeholderName)) {
          return id ? `${placeholder}_${id}` : `${placeholder}_${DEFAULT_PLACEHOLDER_UID}`;
        }
      }
    }

    return id
      ? `${placeholderName}_${id}`
      : `${placeholderName}_${DEFAULT_PLACEHOLDER_UID}`;
  }
}

// packages/sitecore-jss-react/src/components/PlaceholderMetadata.tsx
﻿import React, { ReactNode } from 'react';
import {
  ComponentRendering,
  getDynamicPlaceholderPattern,
  isDynamicPlaceholder,
} from '@sitecore-content-sdk/sitecore-jss/layout';
import { MetadataKind, DEFAULT_PLACEHOLDER_UID } from '@sitecore-content-sdk/sitecore-jss/editing';

/**
 *  Props containing the component data to render.
 */
export interface PlaceholderMetadataProps {
  rendering: ComponentRendering;
  placeholderName?: string;
  children?: ReactNode;
}

export type CodeBlockAttributes = {
  type: string;
  chrometype: string;
  className: string;
  kind: string;
  id?: string;
};

/**
 * A React component to generate metadata blocks for a placeholder or rendering.
 * It utilizes dynamic attributes based on whether the component acts as a placeholder
 * or as a rendering to properly render the surrounding code blocks.
 * @param {object} props The properties passed to the component.
 * @param {ComponentRendering} props.rendering The rendering data.
 * @param {string} [props.placeholderName] The name of the placeholder.
 * @param {JSX.Element} props.children The child components or elements to be wrapped by the metadata code blocks.
 * @returns {JSX.Element} A React fragment containing open and close code blocks surrounding the children elements.
 */
export const PlaceholderMetadata = ({
  rendering,
  placeholderName,
  children,
}: PlaceholderMetadataProps): JSX.Element => {
  const getCodeBlockAttributes = (
    kind: MetadataKind,
    id: string,
    placeholderName?: string
  ): CodeBlockAttributes => {
    const chrometype = placeholderName ? 'placeholder' : 'rendering';

    const attributes: CodeBlockAttributes = {
      type: 'text/sitecore',
      chrometype: chrometype,
      className: 'scpm',
      kind: kind,
    };

    if (kind === MetadataKind.Open) {
      if (chrometype === 'placeholder' && placeholderName) {
        let phId = '';

        for (const placeholder of Object.keys(rendering.placeholders)) {
          if (placeholderName === placeholder) {
            phId = id
              ? `${placeholderName}_${id}`
              : `${placeholderName}_${DEFAULT_PLACEHOLDER_UID}`;
            break;
          }

          // Check if the placeholder is a dynamic placeholder
          if (isDynamicPlaceholder(placeholder)) {
            const pattern = getDynamicPlaceholderPattern(placeholder);

            // Check if the placeholder matches the dynamic placeholder pattern
            if (pattern.test(placeholderName)) {
              phId = id ? `${placeholder}_${id}` : `${placeholder}_${DEFAULT_PLACEHOLDER_UID}`;
              break;
            }
          }
        }

        attributes.id = phId;
      } else {
        attributes.id = id;
      }
    }

    return attributes;
  };

  const renderComponent = (uid: string, placeholderName?: string) => (
    <>
      <code {...getCodeBlockAttributes(MetadataKind.Open, uid, placeholderName)} />
      {children}
      <code {...getCodeBlockAttributes(MetadataKind.Close, uid, placeholderName)} />
    </>
  );

  return <>{renderComponent(rendering.uid, placeholderName)}</>;
};
