// packages/create-content-sdk-app/src/templates/angular/src/app/components/link-list.component.ts
import { Component, computed } from '@angular/core';
import { isFieldValueEmpty } from '@sitecore-content-sdk/content/layout';
import { Field, ScTextDirective, ScLinkDirective, LinkField } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

interface LinkListDatasource {
  children?: {
    results?: Array<{
      field?: {
        link?: LinkField;
      };
    }>;
  };
  field?: {
    title?: Field<string>;
  };
}

interface LinkListFields {
  data?: { datasource?: LinkListDatasource };
}

@Component({
  selector: 'app-link-list',
  imports: [ScTextDirective, ScLinkDirective],
  template: `
    <div [attr.class]="('component link-list ' + styles()).trim()" [attr.id]="renderingId()">
      <div class="component-content">
        @if (!datasource()) {
        <h3>Link List</h3>
        } @else {
        <h3 [scText]="titleField()"></h3>
        <ul>
          @for (row of linkRows(); track $index) {
          <li [class]="itemClass($index, linkRows().length)">
            <div class="field-link">
              <a [scLink]="row.link"></a>
            </div>
          </li>
          }
        </ul>
        }
      </div>
    </div>
  `,
})
export class LinkListComponent extends SxaComponent {
  readonly data = computed(() => (this.fields() as LinkListFields)?.data);

  readonly datasource = computed(() => this.data()?.datasource);

  readonly titleField = computed(() => this.datasource()?.field?.title);

  readonly linkRows = computed(() => {
    const results = this.datasource()?.children?.results;
    if (!Array.isArray(results)) return [] as Array<{ link: LinkField }>;
    return results
      .filter((result) => {
        const link = result?.field?.link;
        return !!link && !isFieldValueEmpty(link);
      })
      .map((result) => ({ link: result.field!.link! }));
  });

  /** SXA-style list row classes: `item{n}`, alternating odd/even (0-based), optional first/last. */
  itemClass(index: number, total: number): string {
    const classes = [`item${index}`, index % 2 === 0 ? 'odd' : 'even'];
    if (index === 0) classes.push('first');
    if (index === total - 1) classes.push('last');
    return classes.join(' ');
  }
}

// packages/create-content-sdk-app/src/templates/nextjs/src/components/LinkList.tsx
﻿import React from 'react';
import { Link as ContentSdkLink, Text, LinkField, TextField } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';

interface LinkListProps extends ComponentProps {
  fields: {
    /**
     * The Integrated graphQL query result. This illustrates the way to access the datasource children.
     */
    data: {
      datasource: {
        children: {
          results: Array<{
            field: {
              link: LinkField;
            };
          }>;
        };
        field: {
          title: TextField;
        };
      };
    };
  };
}

const LinkListItem = ({
  index,
  total,
  field,
}: {
  index: number;
  total: number;
  field: LinkField;
}) => {
  const classNames = [
    `item${index}`,
    index % 2 === 0 ? 'odd' : 'even',
    index === 0 ? 'first' : '',
    index === total - 1 ? 'last' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <li className={classNames}>
      <div className="field-link">
        <ContentSdkLink field={field} />
      </div>
    </li>
  );
};

export const Default = ({ params, fields }: LinkListProps) => {
  const datasource = fields?.data?.datasource;
  const styles = `component link-list ${params.styles || ''}`.trim();
  const id = params.RenderingIdentifier;

  const renderContent = () => {
    if (!datasource) {
      return <h3>Link List</h3>;
    }

    const links = datasource.children.results
      .filter(element => element?.field?.link)
      .map((element, index) => (
        <LinkListItem
          key={`${index}-${element.field?.link}`}
          index={index}
          total={datasource.children.results.length}
          field={element.field.link}
        />
      ));

    return (
      <>
        <Text tag="h3" field={datasource.field?.title} />
        <ul>{links}</ul>
      </>
    );
  };

  return (
    <div className={styles} id={id}>
      <div className="component-content">{renderContent()}</div>
    </div>
  );
};
