// packages/angular/src/placeholder/placeholder-utils.ts
import { Type } from '@angular/core';
import {
  ComponentRendering,
  RouteData,
  isDynamicPlaceholder,
  getDynamicPlaceholderPattern,
} from '@sitecore-content-sdk/content/layout';
import { HIDDEN_RENDERING_NAME } from '@sitecore-content-sdk/content';
import {
  AngularCsdkComponent,
  ComponentMap,
  DEFAULT_EXPORT_NAME,
} from '../components/types';

/**
 * Result of resolving a component for a rendering definition.
 */
export interface ComponentForRendering {
  component: Type<unknown> | null;
  isEmpty: boolean;
}

/**
 * Merged props passed to each child component rendered by a placeholder.
 */
export interface ChildComponentProps {
  fields: { [key: string]: unknown };
  params: { [key: string]: string };
  rendering: ComponentRendering;
}

/**
 * Get the renderings for the specified placeholder from the rendering layout data.
 * Includes dynamic placeholder handling aligned with React's implementation.
 * @param rendering - rendering data
 * @param name - placeholder name
 * @param isEditing - whether editing mode is active
 * @returns array of component renderings
 */
export const getPlaceholderRenderings = (
  rendering: ComponentRendering | RouteData,
  name: string,
  isEditing: boolean
): ComponentRendering[] => {
  let phName = name.slice();
  let placeholdersForRead: Record<string, ComponentRendering[]> | undefined;

  if (rendering?.placeholders) {
    if (isEditing) {
      Object.keys(rendering.placeholders).forEach((key) => {
        const patternPlaceholder = isDynamicPlaceholder(key)
          ? getDynamicPlaceholderPattern(key)
          : null;

        if (patternPlaceholder && patternPlaceholder.test(phName)) {
          phName = key;
        }
      });
      placeholdersForRead = rendering.placeholders;
    } else {
      placeholdersForRead = { ...rendering.placeholders };
      Object.entries(rendering.placeholders).forEach(([key, value]) => {
        const patternPlaceholder = isDynamicPlaceholder(key)
          ? getDynamicPlaceholderPattern(key)
          : null;

        if (patternPlaceholder && patternPlaceholder.test(phName)) {
          placeholdersForRead![phName] = value;
          delete placeholdersForRead![key];
        }
      });
    }
  }

  let result: ComponentRendering[] | null = null;
  if (rendering && placeholdersForRead && Object.keys(placeholdersForRead).length > 0) {
    result = placeholdersForRead[phName] ?? null;
  }

  if (!result) {
    console.warn(
      `Placeholder '${phName}' was not found in the current rendering data`,
      JSON.stringify(rendering, null, 2)
    );
    return [];
  }

  return result;
};

/**
 * Extra inputs to set on each dynamically rendered component (in addition to `fields`, `params`, `rendering`).
 * Keys are Angular `input()` names on the host component.
 * @public
 */
export type PassThroughProps = Readonly<Record<string, unknown>>;

/**
 * Get SXA specific params from Sitecore rendering params.
 * @param rendering - rendering object
 * @returns converted SXA params
 */
export const getSXAParams = (rendering: ComponentRendering): { styles: string } | undefined => {
  if (!rendering.params) return { styles: '' };

  const { GridParameters, Styles } = rendering.params;

  if (GridParameters || Styles) {
    return { styles: `${GridParameters || ''} ${Styles || ''}` };
  }

  return undefined;
};

/**
 * Merge placeholder-level fields/params with per-component fields/params.
 * @param placeholderFields - placeholder-level fields
 * @param placeholderParams - placeholder-level params
 * @param componentRendering - the component rendering data
 * @returns merged child component props
 */
export function getChildComponentProps(
  placeholderFields: { [key: string]: unknown } | undefined,
  placeholderParams: { [key: string]: string } | undefined,
  componentRendering: ComponentRendering
): ChildComponentProps {
  const fields = { ...(placeholderFields || {}), ...(componentRendering.fields || {}) };
  const params = { ...(placeholderParams || {}), ...(componentRendering.params || {}) };
  return {
    fields,
    params: {
      ...params,
      ...getSXAParams(componentRendering),
    },
    rendering: componentRendering,
  };
}

/**
 * Resolve a component type for a rendering definition.
 * Handles hidden renderings, missing components, variant selection, and map lookup.
 * FEaaS/BYOC are intentionally not handled; they fall through to missingComponent.
 * @param renderingDefinition - the rendering to resolve
 * @param placeholderName - current placeholder name (for logging)
 * @param componentMap - the app component map
 * @param hiddenRenderingComponent - optional override for hidden renderings
 * @param missingComponentComponent - optional override for missing/unknown components
 * @returns resolved component info
 */
export const resolveComponentForRendering = (
  renderingDefinition: ComponentRendering,
  placeholderName: string,
  componentMap?: ComponentMap,
  hiddenRenderingComponent?: Type<unknown>,
  missingComponentComponent?: Type<unknown>
): ComponentForRendering => {
  if (renderingDefinition.componentName === HIDDEN_RENDERING_NAME) {
    return {
      component: hiddenRenderingComponent ?? null,
      isEmpty: true,
    };
  }

  if (!renderingDefinition.componentName) {
    return {
      component: null,
      isEmpty: true,
    };
  }

  let entry: Type<unknown> | AngularCsdkComponent | undefined;
  const hasComponentMap = !!(componentMap && componentMap.size > 0);
  if (!hasComponentMap) {
    console.warn(
      `No components were available in component map to service request for component ${renderingDefinition.componentName}`
    );
  } else {
    entry = componentMap!.get(renderingDefinition.componentName);
  }

  if (!entry) {
    console.error(
      `Placeholder ${placeholderName} contains unknown component ${renderingDefinition.componentName}. Ensure that an Angular component exists for it, and that it is registered in your component map.`
    );
    return {
      component: missingComponentComponent ?? null,
      isEmpty: true,
    };
  }

  // If entry is a direct component class (function / class constructor), return it
  if (typeof entry === 'function') {
    return { component: entry, isEmpty: false };
  }

  // AngularCsdkComponent (SXA variants): pick export by FieldNames
  const exportName = renderingDefinition.params?.FieldNames;
  const resolved =
    exportName && exportName !== DEFAULT_EXPORT_NAME
      ? (entry[exportName] as Type<unknown> | undefined)
      : entry.default || entry.Default;

  if (!resolved || typeof resolved !== 'function') {
    const variantLabel = exportName && exportName !== DEFAULT_EXPORT_NAME ? ` (${exportName})` : '';
    console.error(
      `Placeholder ${placeholderName} contains unknown component ${renderingDefinition.componentName}${variantLabel}. Ensure that an Angular component exists for it, and that it is registered in your component map.`
    );
    return {
      component: missingComponentComponent ?? null,
      isEmpty: true,
    };
  }

  return { component: resolved, isEmpty: false };
};

// packages/react/src/components/Placeholder/placeholder-utils.tsx
﻿import React, { ComponentType } from 'react';
import { MissingComponent } from '../MissingComponent';
import { ComponentMap, DEFAULT_EXPORT_NAME, LazyComponentType, ReactModule } from '../sharedTypes';
import {
  ComponentRendering,
  RouteData,
  isDynamicPlaceholder,
  getDynamicPlaceholderPattern,
} from '@sitecore-content-sdk/core/layout';
import { constants } from '@sitecore-content-sdk/core';
import { HiddenRendering } from '../HiddenRendering';
import { FEaaSComponent, FEAAS_COMPONENT_RENDERING_NAME } from '../FEaaSComponent';
import { FEaaSWrapper, FEAAS_WRAPPER_RENDERING_NAME } from '../FEaaSWrapper';
import { BYOCComponent, BYOC_COMPONENT_RENDERING_NAME } from '../BYOCComponent';
import { BYOCWrapper, BYOC_WRAPPER_RENDERING_NAME } from '../BYOCWrapper';
import { PlaceholderProps, RenderedProps } from './models';

/**
 * Get the renderings for the specified placeholder from the rendering data.
 * @param {ComponentRendering | RouteData } rendering rendering data
 * @param {string} name placeholder name
 * @param {boolean} isEditing whether components should be rendered in editing mode
 * @returns {ComponentRendering[]} array of component renderings
 */
export const getPlaceholderRenderings = (
  rendering: ComponentRendering | RouteData,
  name: string,
  isEditing: boolean
) => {
  let result;
  let phName = name.slice();

  /**
   * Process (SXA) dynamic placeholders
   * Find and replace the matching dynamic placeholder e.g 'nameOfContainer-{*}' with the requested e.g. 'nameOfContainer-1'.
   * For Metadata EditMode, we need to keep the raw placeholder name in place.
   */
  if (rendering?.placeholders) {
    Object.keys(rendering.placeholders).forEach((placeholder) => {
      const patternPlaceholder = isDynamicPlaceholder(placeholder)
        ? getDynamicPlaceholderPattern(placeholder)
        : null;

      if (patternPlaceholder && patternPlaceholder.test(phName)) {
        if (isEditing) {
          phName = placeholder;
        } else {
          rendering.placeholders[phName] = rendering.placeholders[placeholder];
          delete rendering.placeholders[placeholder];
        }
      }
    });
  }

  if (rendering && rendering.placeholders && Object.keys(rendering.placeholders).length > 0) {
    result = rendering.placeholders[phName];
  } else {
    result = null;
  }

  if (!result) {
    console.warn(
      `Placeholder '${phName}' was not found in the current rendering data`,
      JSON.stringify(rendering, null, 2)
    );

    return [];
  }

  return result;
};

/**
 * Get SXA specific params from Sitecore rendering params
 * @param {ComponentRendering} rendering rendering object
 * @returns {object} converted SXA params
 */
export const getSXAParams = (rendering: ComponentRendering) => {
  if (!rendering.params) return {};

  const { GridParameters, Styles } = rendering.params;

  return (
    (GridParameters || Styles) && {
      styles: `${GridParameters || ''} ${Styles || ''}`,
    }
  );
};

/**
 * Renders the placeholder when it is empty. The required CSS styles are applied to the placeholder in edit mode.
 * @param {React.ReactNode | React.ReactElement[]} node react node
 * @returns react node
 */
export const renderEmptyPlaceholder = (node: React.ReactNode | React.ReactElement[]) => {
  return <div className="sc-jss-empty-placeholder">{node}</div>;
};

/**
 * Get component props to be passed to the rendered component.
 * @param {PlaceholderProps} placeholderProps current placeholder props
 * @param {ComponentRendering} componentRendering rendering to be rendered
 * @param {string} renderingKey unique key to pass over to rendering props
 * @returns {RenderedProps} props to be passed to the rendered component
 */
export const getRenderedComponentProps = (
  placeholderProps: PlaceholderProps,
  componentRendering: ComponentRendering,
  renderingKey: string
): RenderedProps => {
  const {
    fields: placeholderFields,
    params: placeholderParams,
    ...passThroughProps
  } = placeholderProps;
  delete passThroughProps.missingComponentComponent;
  delete passThroughProps.hiddenRenderingComponent;
  delete passThroughProps.name;
  const fields = { ...(placeholderFields || {}), ...(componentRendering.fields || {}) };
  const params = { ...(placeholderParams || {}), ...(componentRendering.params || {}) };

  return {
    key: renderingKey,
    ...passThroughProps,
    fields,
    params: {
      ...params,
      // Provide SXA styles
      ...getSXAParams(componentRendering),
    },
    rendering: componentRendering,
  };
};

/**
 * Get component implemenation from the component map based on the rendering definition.
 * @param {ComponentRendering} renderingDefinition rendering data
 * @param {string} placeholderName name of current placeholder
 * @param {ComponentMap} componentMap component map for the current app
 * @param {React.ComponentClass} [hiddenRenderingComponent] fallback implementation in to be rendered if the rendering is hidden
 * @param {React.ComponentClass} [missingComponentComponent] fallback implementation in case no component is found in the component map
 * @returns {ContentSDKComponet | null} component implementation or null if no component map is provided
 */
export const getComponentForRendering = (
  renderingDefinition: ComponentRendering,
  placeholderName: string,
  componentMap?: ComponentMap,
  hiddenRenderingComponent?: React.ComponentClass | React.FC,
  missingComponentComponent?: React.ComponentClass | React.FC
) => {
  if (renderingDefinition.componentName === constants.HIDDEN_RENDERING_NAME) {
    return {
      component: hiddenRenderingComponent ?? HiddenRendering,
      isEmpty: true,
    };
  } else if (!renderingDefinition.componentName) {
    console.error(
      `Placeholder ${placeholderName} contains unknown component ${renderingDefinition.componentName}. Ensure that a React component exists for it, and that it is registered in your component-map file.`
    );
    return {
      component: () => <></>,
      isEmpty: true,
    };
  }

  let component = null;
  if (!componentMap || componentMap.size === 0) {
    console.warn(
      `No components were available in component map to service request for component ${renderingDefinition}`
    );
  } else {
    component = componentMap.get(renderingDefinition.componentName);
  }

  if (!component) {
    // Fallback/defaults for Sitecore Component renderings (in case not defined in component map)
    if (renderingDefinition.componentName === FEAAS_COMPONENT_RENDERING_NAME) {
      return {
        component: FEaaSComponent,
      };
    } else if (renderingDefinition.componentName === FEAAS_WRAPPER_RENDERING_NAME) {
      return {
        component: FEaaSWrapper,
      };
    } else if (renderingDefinition.componentName === BYOC_COMPONENT_RENDERING_NAME) {
      return {
        component: BYOCComponent,
      };
    } else if (renderingDefinition.componentName === BYOC_WRAPPER_RENDERING_NAME) {
      // wrapping with error boundary could cause problems in case where parent component uses withPlaceholder HOC and tries to access its children props
      // that's why we need to mark BYOC wrapper dynamic
      return {
        component: BYOCWrapper,
        dynamic: true,
      };
    }
    return {
      component: missingComponentComponent ?? MissingComponent,
      isEmpty: true,
    };
  }

  // Render SXA Rendering Variant if available
  const exportName = renderingDefinition.params?.FieldNames;

  const renderedComponent =
    exportName && exportName !== DEFAULT_EXPORT_NAME
      ? ((component as ReactModule)[exportName] as ComponentType)
      : (component as ReactModule).default ||
        (component as ReactModule).Default ||
        (component as ComponentType);

  // all dynamic elements will have a separate render prop
  return {
    component: renderedComponent,
    dynamic: !!(renderedComponent as LazyComponentType).render?.preload,
    componentType: (component as ReactModule).componentType,
  };
};
