// packages/create-content-sdk-app/src/templates/nextjs-app-router (beta)/src/components/skatepark/RichText.tsx
import React from 'react';
import {
  ComponentParams,
  ComponentRendering,
  RichText as SitecoreRichText,
} from '@sitecore-content-sdk/nextjs';

interface Fields {
  text: { value: string };
}

type RichTextProps = {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
  fields: Fields;
};

export const RichText = (props: RichTextProps) => {
  const { text } = props.fields || {};

  return (
    <div className="component rich-text">
      <div className="component-content">
        {text ? (
          <SitecoreRichText field={text} />
        ) : (
          <span className="is-empty-hint">Rich text</span>
        )}
      </div>
    </div>
  );
};

// packages/create-content-sdk-app/src/templates/angular/src/app/components/richtext/richtext.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RichTextField, RichTextComponent as CSDKRichTextComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-richtext',
  templateUrl: './richtext.component.html',
  standalone: true,
  imports: [CommonModule, CSDKRichTextComponent],
  host: {
    class: 'component rich-text',
    '[class]': 'styles',
    '[attr.id]': 'id',
  },
})
export class RichTextComponent extends SxaComponent implements OnInit {
  text?: RichTextField;

  override ngOnInit() {
    super.ngOnInit();
    this.text = this.rendering.fields?.Text as RichTextField;
  }
}

<div class="component-content">
  @if (text) {
  <sc-rich-text [field]="text"></sc-rich-text>
  } @else {
  <span class="is-empty-hint">Rich text</span>
  }
</div>
