// packages/create-content-sdk-app/src/templates/nextjs/src/components/RichText.tsx
﻿import React, { JSX } from 'react';
import { Field, RichText as ContentSdkRichText } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';

interface Fields {
  Text: Field<string>;
}

export type RichTextProps = ComponentProps & {
  fields: Fields;
};

export const Default = ({ params, fields }: RichTextProps): JSX.Element => {
  const { RenderingIdentifier, styles } = params;
  
  return (
    <div 
      className={`component rich-text ${styles}`}
      id={RenderingIdentifier}
    >
      <div className="component-content">
        {fields ? (
          <ContentSdkRichText field={fields.Text} />
        ) : (
          <span className="is-empty-hint">Rich text</span>
        )}
      </div>
    </div>
  );
};

// packages/create-content-sdk-app/src/templates/angular/src/app/components/richtext/richtext.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RichTextField, RichTextComponent as CSDKRichTextComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-richtext',
  templateUrl: './richtext.component.html',
  standalone: true,
  imports: [CommonModule, CSDKRichTextComponent],
  host: {
    class: 'component rich-text',
    '[class]': 'styles',
    '[attr.id]': 'id',
  },
})
export class RichTextComponent extends SxaComponent implements OnInit {
  text?: RichTextField;

  override ngOnInit() {
    super.ngOnInit();
    this.text = this.rendering.fields?.Text as RichTextField;
  }
}

<div class="component-content">
  @if (text) {
  <sc-rich-text [field]="text"></sc-rich-text>
  } @else {
  <span class="is-empty-hint">Rich text</span>
  }
</div>
