// packages/create-content-sdk-app/src/templates/angular/src/app/shared/layout.component.ts
import { Component, input, computed, effect, inject } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Page, Field, RouteData, ScPlaceholderComponent } from '@sitecore-content-sdk/angular';

interface RouteFields {
  [key: string]: unknown;
  Title?: Field<string>;
}

@Component({
  selector: 'app-layout',
  imports: [ScPlaceholderComponent],
  template: `
    <div [attr.class]="layoutClassAttr()">
      <header class="w-full">
        <div id="header">
          @if (scRoute()) {
            <sc-placeholder name="headless-header" [rendering]="scRoute()!"></sc-placeholder>
          }
        </div>
      </header>
      <main class="min-w-0 w-full flex-1">
        <div id="content" class="w-full min-w-0 max-w-none">
          @if (scRoute()) {
            <sc-placeholder name="headless-main" [rendering]="scRoute()!"></sc-placeholder>
          }
        </div>
      </main>
      <footer class="w-full">
        <div id="footer">
          @if (scRoute()) {
            <sc-placeholder name="headless-footer" [rendering]="scRoute()!"></sc-placeholder>
          }
        </div>
      </footer>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
  `,
})
export class LayoutComponent {
  readonly page = input.required<Page>();

  readonly scRoute = computed(() => this.page().layout?.sitecore?.route as RouteData | null);

  readonly layoutClassAttr = computed(() => {
    const editing = this.page().mode?.isEditing;
    const base = 'flex min-h-screen min-w-0 flex-col';
    return editing ? `${base} editing-mode` : `${base} prod-mode`;
  });

  private readonly titleService = inject(Title);

  constructor() {
    effect(() => {
      const route = this.scRoute();
      if (route) {
        const fields = route.fields as RouteFields | undefined;
        const title = fields?.Title?.value ?? 'Content SDK Page';
        this.titleService.setTitle(title);
      }
    });
  }
}

// packages/create-content-sdk-app/src/templates/nextjs-app-router (beta)/src/Layout.tsx
import React, { JSX } from 'react';
import { Field, Page } from '@sitecore-content-sdk/nextjs';
import Scripts from 'src/Scripts';
import SitecoreStyles from 'components/content-sdk/SitecoreStyles';
import { DesignLibraryLayout } from './DesignLibraryLayout';
import { AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';

interface LayoutProps {
  page: Page;
}

export interface RouteFields {
  [key: string]: unknown;
  Title?: Field;
}

const Layout = ({ page }: LayoutProps): JSX.Element => {
  const { layout, mode } = page;
  const { route } = layout.sitecore;
  const mainClassPageEditing = mode.isEditing ? 'editing-mode' : 'prod-mode';
  return (
    <>
      <Scripts />
      <SitecoreStyles layoutData={layout} />
      {/* root placeholder for the app, which we add components to using route data */}
      <div className={mainClassPageEditing}>
        {mode.isDesignLibrary ? (
          <DesignLibraryLayout />
        ) : (
          <>
            <header>
              <div id="header">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-header"
                    rendering={route}
                  />
                )}
              </div>
            </header>
            <main>
              <div id="content">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-main"
                    rendering={route}
                  />
                )}
              </div>
            </main>
            <footer>
              <div id="footer">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-footer"
                    rendering={route}
                  />
                )}
              </div>
            </footer>
          </>
        )}
      </div>
    </>
  );
};

export default Layout;
