// packages/create-content-sdk-app/src/templates/nextjs-app-router (beta)/src/Layout.tsx
import React, { JSX } from 'react';
import { Field, Page } from '@sitecore-content-sdk/nextjs';
import Scripts from 'src/Scripts';
import SitecoreStyles from 'components/content-sdk/SitecoreStyles';
import { DesignLibraryLayout } from './DesignLibraryLayout';
import { AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';

interface LayoutProps {
  page: Page;
}

export interface RouteFields {
  [key: string]: unknown;
  Title?: Field;
}

const Layout = ({ page }: LayoutProps): JSX.Element => {
  const { layout, mode } = page;
  const { route } = layout.sitecore;
  const mainClassPageEditing = mode.isEditing ? 'editing-mode' : 'prod-mode';
  return (
    <>
      <Scripts />
      <SitecoreStyles layoutData={layout} />
      {/* root placeholder for the app, which we add components to using route data */}
      <div className={mainClassPageEditing}>
        {mode.isDesignLibrary ? (
          <DesignLibraryLayout />
        ) : (
          <>
            <header>
              <div id="header">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-header"
                    rendering={route}
                  />
                )}
              </div>
            </header>
            <main>
              <div id="content">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-main"
                    rendering={route}
                  />
                )}
              </div>
            </main>
            <footer>
              <div id="footer">
                {route && (
                  <AppPlaceholder
                    page={page}
                    componentMap={componentMap}
                    name="headless-footer"
                    rendering={route}
                  />
                )}
              </div>
            </footer>
          </>
        )}
      </div>
    </>
  );
};

export default Layout;

// samples/angular/src/app/shared/layout/layout.component.ts
import { Component, input, computed, effect, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Title } from '@angular/platform-browser';
import { PlaceholderComponent, Page, Field } from '@sitecore-content-sdk/angular';

/**
 * Route fields interface for page title
 */
interface RouteFields {
  [key: string]: unknown;
  Title?: Field<string>;
}

/**
 * Layout component that provides the main structure for Sitecore pages.
 * Renders header, main content, and footer placeholders.
 * @public
 */
@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, PlaceholderComponent],
  template: `
    @if (route()) {
    <div [class]="mainClass()">
      <header>
        <div id="header">
          <sc-placeholder name="headless-header" [rendering]="route()!"></sc-placeholder>
        </div>
      </header>
      <main>
        <div id="content">
          <sc-placeholder name="headless-main" [rendering]="route()!"></sc-placeholder>
        </div>
      </main>
      <footer>
        <div id="footer">
          <sc-placeholder name="headless-footer" [rendering]="route()!"></sc-placeholder>
        </div>
      </footer>
    </div>
    } @else {
    <div class="loading">
      <p>Loading...</p>
    </div>
    }
  `,
  styles: `
    :host {
      display: block;
      min-height: 100vh;
    }

    .editing-mode {
      /* Styles for editing mode */
    }

    .prod-mode {
      /* Styles for production mode */
    }

    .loading {
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
    }

    header {
      width: 100%;
    }

    main {
      flex: 1;
      width: 100%;
    }

    footer {
      width: 100%;
    }
  `,
})
export class LayoutComponent {
  /**
   * Page data from Sitecore
   */
  readonly page = input.required<Page>();

  /**
   * Current route data derived from page
   */
  readonly route = computed(() => this.page().layout?.sitecore?.route ?? null);

  /**
   * Main container CSS class based on editing mode
   */
  readonly mainClass = computed(() => (this.page().mode?.isEditing ? 'editing-mode' : 'prod-mode'));

  private readonly titleService = inject(Title);

  constructor() {
    // Effect to update the page title when the page changes
    effect(() => {
      const route = this.route();
      if (route) {
        const fields = route.fields as RouteFields | undefined;
        const title = fields?.Title?.value ?? 'Page';
        this.titleService.setTitle(title);
      }
    });
  }
}
