// packages/react/src/components/FieldMetadata.tsx
﻿import React, { JSX } from 'react';
import { MetadataKind } from '@sitecore-content-sdk/core/editing';

interface FieldMetadataProps {
  metadata: { [key: string]: unknown };
  children: React.ReactNode;
}

/**
 * The component which renders field metadata markup
 * @param {FieldMetadataProps} props the props of the component
 * @returns metadata markup wrapped around children
 */
export const FieldMetadata = (props: FieldMetadataProps): JSX.Element => {
  const data = JSON.stringify(props.metadata);
  const attributes = {
    type: 'text/sitecore',
    chrometype: 'field',
    className: 'scpm',
  };
  const codeOpenAttributes = { ...attributes, kind: MetadataKind.Open };
  const codeCloseAttributes = { ...attributes, kind: MetadataKind.Close };

  return (
    <>
      <code {...codeOpenAttributes}>{data}</code>
      {props.children}
      <code {...codeCloseAttributes}></code>
    </>
  );
};

FieldMetadata.displayName = 'FieldMetadata';

// packages/angular/src/components/field-metadata.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MetadataKind } from '@sitecore-content-sdk/core/editing';

/**
 * Component that wraps field content with metadata markup for chromes hydration in Pages.
 * This is used internally by field components to support editing mode.
 * @public
 */
@Component({
  selector: 'sc-field-metadata',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <code
      type="text/sitecore"
      chrometype="field"
      class="scpm"
      [attr.kind]="openKind"
      >{{ metadataJson }}</code
    >
    <ng-content></ng-content>
    <code
      type="text/sitecore"
      chrometype="field"
      class="scpm"
      [attr.kind]="closeKind"
    ></code>
  `,
})
export class FieldMetadataComponent {
  /**
   * The metadata object to be serialized and included in the opening code tag
   */
  @Input({ required: true }) metadata!: { [key: string]: unknown };

  /**
   * MetadataKind.Open constant for template
   */
  protected readonly openKind = MetadataKind.Open;

  /**
   * MetadataKind.Close constant for template
   */
  protected readonly closeKind = MetadataKind.Close;

  /**
   * Serialized metadata JSON string
   */
  protected get metadataJson(): string {
    return JSON.stringify(this.metadata);
  }
}
